# Generated by Django 5.2 on 2025-04-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_item_market_name_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='market_name',
            field=models.CharField(default='Walmart', max_length=100),
        ),
    ]
